In [2]:
import pandas as pd

In [2]:
ad_rev=pd.read_csv("sod_adrevenue.csv")

In [3]:
ad_rev.query("user_cumulative_iap_revenue<0")
# event_time
#user_install_time
# user_country is missing 1807

Empty DataFrame
Columns: [user_id, event_time, user_point_in_lifetime, user_country, user_device_platform, user_marketing_user, event_type, game_name, user_install_time, user_cumulative_iap_revenue, user_cumulative_iap_payments, user_payer_user, event_revenue_gross_usd, user_rank]
Index: []

In [4]:
# user_point_in_lifetime : number of days he has registered
# user_marketing_user : is user came from Ads
#user_cumulative_iap_revenue: user commulative revenue in app
# user_cumulative_iap_payments: user commulative transaction in app
ad_rev.query("user_point_in_lifetime<0")

Empty DataFrame
Columns: [user_id, event_time, user_point_in_lifetime, user_country, user_device_platform, user_marketing_user, event_type, game_name, user_install_time, user_cumulative_iap_revenue, user_cumulative_iap_payments, user_payer_user, event_revenue_gross_usd, user_rank]
Index: []

In [16]:
# null values : 1807
#duplicates rows:  17 
# check logic 
# datatype : user_install_time, event_time
# uniqueness and consistency  , 35232 userId is noth matched with register table , 
#           107442 user_id is not in ad_revenue tabel (it is possibel )
ad_rev.merge(reg, on='user_id',how='right').query("event_time_x.isna()")['user_id'].nunique()

107442

In [6]:
ad_rev.info()

<class 'pandas.DataFrame'>
RangeIndex: 1778307 entries, 0 to 1778306
Data columns (total 14 columns):
 #   Column                        Dtype
---  ------                        -----
 0   user_id                       str
 1   event_time                    str
 2   user_point_in_lifetime        int64
 3   user_country                  str
 4   user_device_platform          str
 5   user_marketing_user           bool
 6   event_type                    str
 7   game_name                     str
 8   user_install_time             str
 9   user_cumulative_iap_revenue   float64
 10  user_cumulative_iap_payments  int64
 11  user_payer_user               bool
 12  event_revenue_gross_usd       float64
 13  user_rank                     int64
dtypes: bool(2), float64(2), int64(3), str(7)
memory usage: 371.5 MB

In [7]:
rev=pd.read_csv("sod_revenue.csv")

In [8]:
rev['user_id'].count()

np.int64(12363)

In [17]:
# check null values : 93 user_country
# check duplicates rows: 0   
# check logic :22, event_revenue_gross_usd is in negative
# datatype :  user_install_time, event_time  
# uniqueness and consistency : 2007 users are in revenue table nut not in register tabel 
rev.merge(reg, on='user_id',how='left').query("event_time_y.isna()")['user_id'].nunique()

2007

In [19]:

#event_time
#user_install_time
# user_country is missing 93 
#

In [9]:
ad_rev.shape

(1778307, 14)

In [21]:
rev[rev['user_id']=='0d94c274-5d96-4abf-94dd-b48c36076003']

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,user_cumulative_iap_payments,user_payer_user,event_revenue_gross_usd,event_item_id,user_rank
6810,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-24 20:16:36.520000,944,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,846.52,148,True,19.99,com.superoverdrive.itembundle4thcrate.1999,30
6811,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-24 20:20:57.298000,944,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,847.51,149,True,0.99,com.superoverdrive.itemgold.06,30
6812,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-24 20:21:22.119000,944,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,852.50,150,True,4.99,com.superoverdrive.itemgold.01,30
6826,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-25 15:30:52.861000,945,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,872.49,151,True,19.99,com.superoverdrive.itembundlerank15.4999,30
6961,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-28 03:50:23.873000,948,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,873.48,152,True,0.99,com.superoverdrive.itemgold.06,30
6963,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-28 11:22:44.417000,948,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,874.47,153,True,0.99,com.superoverdrive.itemgold.06,30
8674,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-18 00:39:33.888000,937,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,784.57,143,True,0.99,com.superoverdrive.itemgold.06,30
8675,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-18 00:46:01.862000,937,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,785.56,144,True,0.99,com.superoverdrive.itemgold.06,30
8676,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-18 00:57:58.370000,937,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,805.55,145,True,19.99,com.superoverdrive.itembundlerank15.4999,30
8724,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-18 14:02:06.858000,938,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,825.54,146,True,19.99,com.superoverdrive.itembundle.shotgun.1999,30
8777,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-10 12:45:54.887000,930,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,714.67,133,True,0.99,com.superoverdrive.itemgold.06,30
8778,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-10 12:55:22.984000,930,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,715.66,134,True,0.99,com.superoverdrive.itemgold.06,30
8862,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-13 00:17:46.400000,932,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,735.65,135,True,19.99,com.superoverdrive.itembundlerank15.4999,30
9159,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-21 19:31:59.207000,941,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,826.53,147,True,0.99,com.superoverdrive.itemgold.06,30
9360,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 20:26:58.115000,935,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,755.64,136,True,19.99,com.superoverdrive.itembundle4thboost.1999,30
9361,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 20:29:37.446000,935,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,756.63,137,True,0.99,com.superoverdrive.itemgold.06,30
9362,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 20:31:00.542000,935,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,757.62,138,True,0.99,com.superoverdrive.itemgold.06,30
9363,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 20:32:24.366000,935,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,758.61,139,True,0.99,com.superoverdrive.itemgold.06,30
9364,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 20:40:54.059000,935,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,763.60,140,True,4.99,com.superoverdrive.itemgold.01,30
9366,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 21:02:47.010000,935,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,773.59,141,True,9.99,com.superoverdrive.itembundle4thboost.999,30
9367,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 21:06:59.145000,935,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,783.58,142,True,9.99,com.superoverdrive.itemgold.02,30
11519,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-02 19:05:03.104000,922,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,646.85,115,True,0.99,com.superoverdrive.itemgold.06,30
11520,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-02 19:50:14.126000,922,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,647.84,116,True,0.99,com.superoverdrive.itemgold.06,30
11521,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-02 20:38:35.883000,922,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,648.83,117,True,0.99,com.superoverdrive.itemgold.06,30
11523,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-02 21:26:17.341000,922,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,649.82,118,True,0.99,com.superoverdrive.itemgold.06,30
11524,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-02 21:27:24.625000,922,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,654.81,119,True,4.99,com.superoverdrive.itemgold.01,30
11536,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-03 15:12:54.455000,923,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,659.80,120,True,4.99,com.superoverdrive.itemgold.01,30
11537,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-03 19:10:05.605000,923,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,679.79,121,True,19.99,com.superoverdrive.itembundlerank15.4999,30
11540,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-03 22:06:30.077000,923,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,699.78,122,True,19.99,com.superoverdrive.itembundleprecision.1999,30
11541,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-03 22:08:48.725000,923,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,700.77,123,True,0.99,com.superoverdrive.itemgold.06,30
11542,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-03 22:10:33.077000,923,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,705.76,124,True,4.99,com.superoverdrive.itemgold.01,30
11564,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-05 23:23:27.042000,925,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,706.75,125,True,0.99,com.superoverdrive.itemgold.06,30
11573,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-06 14:02:46.543000,926,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,707.74,126,True,0.99,com.superoverdrive.itemgold.06,30
11575,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-06 18:16:17.786000,926,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,708.73,127,True,0.99,com.superoverdrive.itemgold.06,30
11576,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-06 18:17:11.344000,926,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,709.72,128,True,0.99,com.superoverdrive.itemgold.06,30
11579,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-06 21:57:28.322000,926,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,710.71,129,True,0.99,com.superoverdrive.itemgold.06,30
11587,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-07 12:48:03.790000,927,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,711.70,130,True,0.99,com.superoverdrive.itemgold.06,30
11588,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-07 13:47:21.523000,927,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,712.69,131,True,0.99,com.superoverdrive.itemgold.06,30
11604,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-08 14:50:34.296000,928,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,713.68,132,True,0.99,com.superoverdrive.itemgold.06,30
11613,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-29 13:22:13.656000,949,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,875.46,154,True,0.99,com.superoverdrive.itemgold.06,30
11615,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-29 17:36:13.907000,949,US,Android,True,revenue,Super Overdrive,2017-06-24 03:45:02.416000,876.45,155,True,0.99,com.superoverdrive.itemgold.06,30

In [22]:
ad_rev[ad_rev['user_id']=='0d94c274-5d96-4abf-94dd-b48c36076003']

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,user_cumulative_iap_payments,user_payer_user,event_revenue_gross_usd,user_rank
609891,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-18 00:57:36.867000,937,US,Android,True,ad_revenue,Super Overdrive,2017-06-24 03:45:02.416000,825.54,146,True,0.0403,30
610573,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-18 01:27:48.997000,937,US,Android,True,ad_revenue,Super Overdrive,2017-06-24 03:45:02.416000,825.54,146,True,0.0403,30
1501579,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 21:19:36.280000,935,US,Android,True,ad_revenue,Super Overdrive,2017-06-24 03:45:02.416000,783.58,142,True,0.0065,30
1524996,0d94c274-5d96-4abf-94dd-b48c36076003,2020-01-15 23:39:22.320000,935,US,Android,True,ad_revenue,Super Overdrive,2017-06-24 03:45:02.416000,783.58,142,True,0.0065,30

In [11]:
reg=pd.read_csv("sod_register.csv")

In [13]:
# null values : 188 user_counytry
# duplicates rows: 0    
# check logic :
# datatype :  user_install_time, event_time  
# uniqueness 
reg.info()

<class 'pandas.DataFrame'>
RangeIndex: 181894 entries, 0 to 181893
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   user_id                 181894 non-null  str
 1   event_time              181894 non-null  str
 2   user_point_in_lifetime  181894 non-null  int64
 3   user_country            181706 non-null  str
 4   user_device_platform    181894 non-null  str
 5   user_marketing_user     181894 non-null  bool
 6   user_session_id         181894 non-null  int64
 7   event_type              181894 non-null  str
 8   game_name               181894 non-null  str
 9   user_install_time       181894 non-null  str
dtypes: bool(1), int64(2), str(7)
memory usage: 33.4 MB

In [12]:
reg.query("user_point_in_lifetime==0")
#event_time
#user_install_time
# user_country is missing 188
# No duplicates rows

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,user_session_id,event_type,game_name,user_install_time
0,0c2b023e-880d-49b9-b797-255940eced14,2020-01-01 17:52:52.646000,0,UA,iOS,True,1577901172648,register,Super Overdrive,2020-01-01 17:52:52.648000
1,3996ff3f-e710-4370-93b1-e604175b8bfb,2020-01-01 17:58:41.699000,0,CL,iOS,False,1577901521701,register,Super Overdrive,2020-01-01 17:58:41.701000
2,e4349066-a3c4-4185-9146-b536d4daa0a3,2020-01-01 18:14:08.822000,0,BR,Android,False,1577902448824,register,Super Overdrive,2020-01-01 18:14:08.824000
3,20da4cc5-6ccc-4ef7-a326-d5c4196f0e93,2020-01-01 18:26:34.531000,0,FR,Android,False,1577903194533,register,Super Overdrive,2020-01-01 18:26:34.533000
4,e9dafcf4-7824-42c9-bf56-18e367d6a25f,2020-01-01 18:54:03.526000,0,FR,Android,False,1577904843528,register,Super Overdrive,2020-01-01 18:54:03.528000
...,...,...,...,...,...,...,...,...,...,...
181889,14fba79c-ff4b-44b0-96bd-420f16546583,2020-01-28 00:59:55.192000,0,US,iOS,False,1580173195194,register,Super Overdrive,2020-01-28 00:59:55.194000
181890,1219d70e-0a02-483e-ba6c-a4fe503daae4,2020-01-28 01:08:30.004000,0,US,Android,False,1580173710006,register,Super Overdrive,2020-01-28 01:08:30.006000
181891,dfc1bb33-a491-4d70-bab9-feea2e580c8a,2020-01-28 01:08:45.224000,0,US,iOS,True,1580173725226,register,Super Overdrive,2020-01-28 01:08:45.226000
181892,be53abe2-24fe-4b8f-afe9-2591cce44bc1,2020-01-28 01:10:11.758000,0,US,Android,False,1580173811760,register,Super Overdrive,2020-01-28 01:10:11.760000
181893,d5b7dd99-7c16-464f-bd76-5ca2258ff82a,2020-01-28 01:19:49.685000,0,CO,Android,False,1580174389687,register,Super Overdrive,2020-01-28 01:19:49.687000

In [15]:
reg.info()

<class 'pandas.DataFrame'>
RangeIndex: 181894 entries, 0 to 181893
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   user_id                 181894 non-null  str
 1   event_time              181894 non-null  str
 2   user_point_in_lifetime  181894 non-null  int64
 3   user_country            181706 non-null  str
 4   user_device_platform    181894 non-null  str
 5   user_marketing_user     181894 non-null  bool
 6   user_session_id         181894 non-null  int64
 7   event_type              181894 non-null  str
 8   game_name               181894 non-null  str
 9   user_install_time       181894 non-null  str
dtypes: bool(1), int64(2), str(7)
memory usage: 33.4 MB

In [16]:
reg[reg['user_session_id']==1577913772594]

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,user_session_id,event_type,game_name,user_install_time
22,c0fe372a-7fe1-4753-bb45-cb9226fdfddf,2020-01-01 21:22:52.592000,0,MX,Android,True,1577913772594,register,Super Overdrive,2020-01-01 21:22:52.594000
100600,b7ae3110-3e0d-405d-bc51-2a414920d35b,2020-01-01 21:22:52.592000,0,CO,Android,False,1577913772594,register,Super Overdrive,2020-01-01 21:22:52.594000

In [13]:
session=pd.read_csv("sod_session_start.csv")

In [18]:
reg.query("user_id=='9548245a-b26c-4a0a-904e-300cc1a63a51'")

Empty DataFrame
Columns: [user_id, event_time, user_point_in_lifetime, user_country, user_device_platform, user_marketing_user, user_session_id, event_type, game_name, user_install_time]
Index: []

In [19]:
# null values : user_country missing 2199
#duplicates rows: 0
# check logic : 
# datatype : user_install_time, event_time
# uniqueness and consistency :  80621 userId is noth matched with register table 
session.merge(reg,on='user_id', how='left').query("event_time_y.isna()")

,user_id,event_time_x,user_point_in_lifetime_x,user_country_x,user_device_platform_x,user_marketing_user_x,user_session_id_x,event_type_x,game_name_x,user_install_time_x,...,user_rank,event_time_y,user_point_in_lifetime_y,user_country_y,user_device_platform_y,user_marketing_user_y,user_session_id_y,event_type_y,game_name_y,user_install_time_y
0,bf9ee84b-5487-45a1-8e04-6d02a01744b3,2020-01-01 20:54:00.551000,8,MX,Android,False,1577912040552,session_start,Super Overdrive,2019-12-23 22:44:36.048000,...,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,9548245a-b26c-4a0a-904e-300cc1a63a51,2020-01-01 20:55:18.242000,363,NL,Android,False,1577912118243,session_start,Super Overdrive,2019-01-03 20:08:40.533000,...,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,e255ba6e-db2b-495c-99e5-296c929c6bab,2020-01-01 20:57:11.073000,7,US,Android,True,1577912231074,session_start,Super Overdrive,2019-12-25 03:05:49.847000,...,14.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,35fdeb2f-2d37-4cda-a70a-4e7d3340a1ff,2020-01-01 20:57:26.057000,9,US,Android,False,1577912246058,session_start,Super Overdrive,2019-12-23 10:27:11.092000,...,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,441da3ec-b3ea-41b1-b3f6-38293da319a4,2020-01-01 21:01:09.570000,4,US,iOS,False,1577912469571,session_start,Super Overdrive,2019-12-28 16:24:24.381000,...,9.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1981944,f84138e4-c34f-48d3-94fe-fdd585f7497a,2020-01-30 20:50:37.696000,256,HR,Android,False,1580417437697,session_start,Super Overdrive,2019-05-19 20:49:09.546000,...,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981950,29b0008f-9741-4c22-a021-d7d4df888119,2020-01-30 20:53:14.578000,306,ID,Android,False,1580417594579,session_start,Super Overdrive,2019-03-30 06:59:44.701000,...,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981954,2f353e58-2c78-429d-850e-f7ff5e84fd33,2020-01-30 20:57:36.820000,66,NI,Android,False,1580417856821,session_start,Super Overdrive,2019-11-25 00:23:40.867000,...,24.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981955,22857e17-b032-49ee-a27b-2a1b8c47a199,2020-01-30 20:57:37.275000,69,GB,Android,False,1580417857276,session_start,Super Overdrive,2019-11-22 11:29:20.254000,...,21.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1981958,6afc0a35-9bd5-4dec-9d64-86b111e2e821,2020-01-30 20:58:02.637000,382,PL,Android,False,1580417882638,session_start,Super Overdrive,2019-01-13 11:08:57.989000,...,13.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
session.query("event_session_length<0")
#event_time change datatype
# user_country missing 2199
#user_install_time
# user_rank int  and 1 missing

Empty DataFrame
Columns: [user_id, event_time, user_point_in_lifetime, user_country, user_device_platform, user_marketing_user, user_session_id, event_type, game_name, user_install_time, user_cumulative_iap_revenue, user_cumulative_iap_payments, event_session_length, user_payer_user, user_rank]
Index: []

In [21]:
session['user_rank'].value_counts()

user_rank
30.0    231244
1.0     230544
8.0      82785
10.0     82356
3.0      80937
6.0      79270
11.0     78093
7.0      76429
5.0      76203
2.0      76082
9.0      75225
12.0     73000
4.0      67372
13.0     66652
15.0     64215
16.0     59415
14.0     54684
17.0     51612
20.0     44504
18.0     43710
19.0     41160
21.0     38668
22.0     35384
23.0     30917
25.0     28722
24.0     27476
26.0     26140
27.0     22849
28.0     19290
29.0     17022
Name: count, dtype: int64

In [3]:
battle=pd.read_csv("sod_battle_short.csv")
# user_country is misssing 3458
# event_time datatype
# user_install_time datatype

In [23]:
battle.info()

<class 'pandas.DataFrame'>
RangeIndex: 3231358 entries, 0 to 3231357
Data columns (total 18 columns):
 #   Column                        Dtype
---  ------                        -----
 0   user_id                       str
 1   event_time                    str
 2   user_point_in_lifetime        int64
 3   user_country                  str
 4   user_device_platform          str
 5   user_marketing_user           bool
 6   event_type                    str
 7   game_name                     str
 8   user_install_time             str
 9   user_cumulative_iap_revenue   float64
 10  user_cumulative_iap_payments  int64
 11  user_payer_user               bool
 12  event_battle_result           str
 13  custom_battle_type            str
 14  event_battle_duration         int64
 15  user_cumulative_battles       int64
 16  custom_map_id                 int64
 17  user_rank                     int64
dtypes: bool(2), float64(1), int64(6), str(9)
memory usage: 813.4 MB

In [24]:
battle

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,user_cumulative_iap_payments,user_payer_user,event_battle_result,custom_battle_type,event_battle_duration,user_cumulative_battles,custom_map_id,user_rank
0,9b685c09-524a-43e2-a6f9-b970a438fd33,2020-01-01 01:47:39.837000,2,RU,Android,False,battle,Super Overdrive,2019-12-29 08:38:21.177000,0.0,0,False,2-Star Win,campaign,141,138,203,11
1,2b31d675-2007-4689-9f0c-cd67bb3e04c3,2020-01-01 01:47:45.451000,0,VE,Android,False,battle,Super Overdrive,2019-12-31 20:00:28.676000,0.0,0,False,3-Star Win,campaign,177,10,205,3
2,139b74ef-3178-42c1-a4b5-6f8e8b490af3,2020-01-01 01:48:52.189000,46,US,Android,False,battle,Super Overdrive,2019-11-15 15:56:15.092000,0.0,0,False,3-Star Win,campaign,200,1398,505,30
3,044d0f29-97b7-4abe-874c-38161bc5cf29,2020-01-01 01:48:59.888000,0,MX,Android,False,battle,Super Overdrive,2020-01-01 00:58:12.397000,0.0,0,False,2-Star Win,campaign,173,12,204,2
4,57e63954-a7ca-4af1-9ae4-a4aed0f89334,2020-01-01 01:49:15.450000,1,US,Android,False,battle,Super Overdrive,2019-12-30 04:45:54.467000,0.0,0,False,2-Star Win,campaign,215,16,206,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3231353,84bb7e2c-3656-473d-addc-78a53e9a0411,2020-01-31 23:35:41.527000,1042,CA,iOS,False,battle,Super Overdrive,2017-03-25 17:27:18.042000,0.0,0,False,1-Star Win,campaign,83,67324,404,30
3231354,22aef3f0-4c8d-46d5-ba27-e432acfd730a,2020-01-31 23:36:02.916000,11,US,Android,True,battle,Super Overdrive,2020-01-20 01:03:35.359000,0.0,0,False,3-Star Win,campaign,218,310,601,19
3231355,d1316cfd-c37d-4980-aff7-fe1c5492db7a,2020-01-31 23:36:07.048000,0,GR,Android,False,battle,Super Overdrive,2020-01-31 22:39:05.389000,0.0,0,False,Loss,campaign,184,11,301,2
3231356,a5dd871a-bc54-4371-a1fb-226612035639,2020-01-31 23:37:11.606000,2,MX,Android,True,battle,Super Overdrive,2020-01-29 20:03:25.577000,0.0,0,False,1-Star Win,campaign,115,84,204,10
3231357,0ba8e642-e851-4b0f-a7ab-4befe98878f9,2020-01-31 23:37:12.854000,35,EC,Android,False,battle,Super Overdrive,2019-12-27 19:11:30.088000,0.0,0,False,1-Star Win,campaign,98,278,701,18

In [23]:
rev

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,user_cumulative_iap_payments,user_payer_user,event_revenue_gross_usd,event_item_id,user_rank
0,f177e97c-4f0e-4820-b202-706f77839fe3,2020-01-23 21:47:22.175000,8,BR,Android,False,revenue,Super Overdrive,2020-01-15 20:35:55.409000,2.97,3,True,0.99,com.superoverdrive.itemgold.06,17
1,f177e97c-4f0e-4820-b202-706f77839fe3,2020-01-23 21:48:05.262000,8,BR,Android,False,revenue,Super Overdrive,2020-01-15 20:35:55.409000,3.96,4,True,0.99,com.superoverdrive.itemgold.06,17
2,06fc31b3-887b-4309-9ea9-fe2d06471629,2020-01-24 06:53:43.865000,4,US,iOS,False,revenue,Super Overdrive,2020-01-20 06:01:41.207000,0.99,1,True,0.99,com.superoverdrive.itembundlespecial.9999,5
3,d1f252fc-30e5-4377-af7b-ce98a7f21f43,2020-01-24 16:55:59.090000,16,US,Android,False,revenue,Super Overdrive,2020-01-08 00:28:52.021000,4.99,1,True,4.99,com.superoverdrive.itemgold.01,9
4,ee24a1dc-379d-4fd6-87a5-12969173e103,2020-01-24 18:02:08.691000,0,US,Android,True,revenue,Super Overdrive,2020-01-24 01:57:28.926000,0.99,1,True,0.99,com.superoverdrive.itembundlespecial.9999,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12358,ce009465-7f8a-4232-b1d4-8e4d51c569d4,2020-01-14 13:35:36.286000,5,BR,Android,False,revenue,Super Overdrive,2020-01-08 19:32:39.475000,0.99,1,True,0.99,com.superoverdrive.itemgold.06,12
12359,d7f64e4a-c06d-4b72-ab08-ac7396b02751,2020-01-14 16:20:23.853000,877,US,Android,False,revenue,Super Overdrive,2017-08-19 17:32:21.658000,119.93,7,True,19.99,com.superoverdrive.itembundle4thboost.1999,30
12360,d7f64e4a-c06d-4b72-ab08-ac7396b02751,2020-01-14 16:37:13.132000,877,US,Android,False,revenue,Super Overdrive,2017-08-19 17:32:21.658000,139.92,8,True,19.99,com.superoverdrive.itemgold.03,30
12361,e0005ced-4260-4c06-9710-606812170b54,2020-01-14 17:23:27.768000,3,IT,iOS,True,revenue,Super Overdrive,2020-01-11 13:10:41.844000,19.98,2,True,9.99,com.superoverdrive.itembundle4thboost.999,12
12362,4883bf19-2436-4b2e-87e5-8b1b904e537a,2020-01-14 18:44:33.271000,0,SK,Android,False,revenue,Super Overdrive,2020-01-14 07:58:38.525000,0.99,1,True,0.99,com.superoverdrive.itembundlespecial.9999,6

In [ ]:
session.info()

In [ ]:
battle.query("user_id=='7f8740ad-2330-4437-996f-b17d3536e1c9'").sort_values(by='event_time',ascending=False)

In [ ]:
# no dupliactes rows
# user_country is null 3458
# event_time user_install_time
battle

In [ ]:
battle.info()

In [ ]:
battle.isna().sum()

In [ ]:
# check null values : 3458 
# check duplicates rows:  56  
# check logic 
# datatype : user_install_time, event_time
# uniqueness and consistency : 48891

battle.merge(reg, on='user_id',how='left').query("event_time_y.isna()")['user_id'].nunique()

In [ ]:
battle.query("user_id=='d7f64e4a-c06d-4b72-ab08-ac7396b02751'").sort_values(by='user_cumulative_iap_revenue',ascending=False)

In [ ]:
rev.query("user_id=='d7f64e4a-c06d-4b72-ab08-ac7396b02751'").sort_values(by='user_cumulative_iap_revenue',ascending=False).loc[12360]

In [ ]:
rev.shape[0]

In [ ]:
ad_rev.query("user_id=='d7f64e4a-c06d-4b72-ab08-ac7396b02751'").sort_values(by='user_cumulative_iap_revenue',ascending=False).loc[743653]

In [ ]:
battle.info()

In [ ]:
session.query("user_id=='d7f64e4a-c06d-4b72-ab08-ac7396b02751'").sort_values(by='user_cumulative_iap_revenue',ascending=False).loc[1892073]

In [ ]:
reg[reg['user_id']=='d7f64e4a-c06d-4b72-ab08-ac7396b02751']

In [ ]:
reg

In [ ]:
register_users = set(reg["user_id"].dropna().unique())

for name, df in {
    "session": session,
    "ad_revenue": ad_rev,
    "revenue": rev,
    "battle": battle
}.items():
    event_users = set(df["user_id"].dropna().unique())
    missing_users = event_users - register_users

    print(
        name,
        "Unique event users:", len(event_users),
        "Users missing from register:", len(missing_users)
    )

In [ ]:
register_users = set(reg["user_id"].dropna().unique())

session_missing = session[
    ~session["user_id"].isin(register_users)
]

session_missing["user_install_time"] = pd.to_datetime(
    session_missing["user_install_time"],
    errors="coerce"
)

print(session_missing["user_install_time"].describe())
print(session_missing["user_install_time"].min())
print(session_missing["user_install_time"].max())

In [ ]:
print("Registered users:")
print(reg["user_install_time"].min())
print(reg["user_install_time"].max())

print("\nUsers missing from register:")
print(session_missing["user_install_time"].min())
print(session_missing["user_install_time"].max())

In [28]:
reg['user_id'].value_counts()

user_id
0c2b023e-880d-49b9-b797-255940eced14    1
3996ff3f-e710-4370-93b1-e604175b8bfb    1
e4349066-a3c4-4185-9146-b536d4daa0a3    1
20da4cc5-6ccc-4ef7-a326-d5c4196f0e93    1
e9dafcf4-7824-42c9-bf56-18e367d6a25f    1
                                       ..
14fba79c-ff4b-44b0-96bd-420f16546583    1
1219d70e-0a02-483e-ba6c-a4fe503daae4    1
dfc1bb33-a491-4d70-bab9-feea2e580c8a    1
be53abe2-24fe-4b8f-afe9-2591cce44bc1    1
d5b7dd99-7c16-464f-bd76-5ca2258ff82a    1
Name: count, Length: 181894, dtype: int64

In [37]:
ad_rev.head(1)

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,user_cumulative_iap_payments,user_payer_user,event_revenue_gross_usd,user_rank
0,25e77e15-40d6-4d11-a67d-fbb9626b5d33,2020-01-01 01:11:04.647000,774,US,iOS,False,ad_revenue,Super Overdrive,2017-11-17 06:11:31.840000,0.0,0,False,0.0015,30

In [38]:
rev.head(1)

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,user_cumulative_iap_payments,user_payer_user,event_revenue_gross_usd,event_item_id,user_rank
0,f177e97c-4f0e-4820-b202-706f77839fe3,2020-01-23 21:47:22.175000,8,BR,Android,False,revenue,Super Overdrive,2020-01-15 20:35:55.409000,2.97,3,True,0.99,com.superoverdrive.itemgold.06,17

In [44]:
rev['user_point_in_lifetime']=pd.to_numeric(rev['user_point_in_lifetime'])
ad_rev['user_point_in_lifetime']=pd.to_numeric(ad_rev['user_point_in_lifetime'])

In [55]:
remp_Df=rev.merge(ad_rev, on ='user_id',how='outer').groupby(['user_point_in_lifetime_x','user_point_in_lifetime_y']).agg(
    ad_rev = ('event_revenue_gross_usd_y','sum'),
    rev = ('event_revenue_gross_usd_x','sum')
).reset_index()

In [51]:
ad_rev['user_point_in_lifetime'].max() #1179

np.int64(1179)

In [52]:
rev['user_point_in_lifetime'].max()

np.int64(1132)

In [59]:
remp_Df.query("user_point_in_lifetime_y.isna()")

Empty DataFrame
Columns: [user_point_in_lifetime_x, user_point_in_lifetime_y, ad_rev, rev]
Index: []

In [29]:
battle['game_name'].value_counts()

game_name
Super Overdrive    3231358
Name: count, dtype: int64

In [4]:
battle=battle.assign(
    event_date = lambda x : pd.to_datetime(x['event_time']).dt.date,
    event_timex = lambda x : pd.to_datetime(x['event_time']).dt.time
)

In [58]:
battle

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,user_cumulative_iap_payments,user_payer_user,event_battle_result,custom_battle_type,event_battle_duration,user_cumulative_battles,custom_map_id,user_rank,event_date,event_timex
0,9b685c09-524a-43e2-a6f9-b970a438fd33,2020-01-01 01:47:39.837000,2,RU,Android,False,battle,Super Overdrive,2019-12-29 08:38:21.177000,0.0,0,False,2-Star Win,campaign,141,138,203,11,2020-01-01,01:47:39.837000
1,2b31d675-2007-4689-9f0c-cd67bb3e04c3,2020-01-01 01:47:45.451000,0,VE,Android,False,battle,Super Overdrive,2019-12-31 20:00:28.676000,0.0,0,False,3-Star Win,campaign,177,10,205,3,2020-01-01,01:47:45.451000
2,139b74ef-3178-42c1-a4b5-6f8e8b490af3,2020-01-01 01:48:52.189000,46,US,Android,False,battle,Super Overdrive,2019-11-15 15:56:15.092000,0.0,0,False,3-Star Win,campaign,200,1398,505,30,2020-01-01,01:48:52.189000
3,044d0f29-97b7-4abe-874c-38161bc5cf29,2020-01-01 01:48:59.888000,0,MX,Android,False,battle,Super Overdrive,2020-01-01 00:58:12.397000,0.0,0,False,2-Star Win,campaign,173,12,204,2,2020-01-01,01:48:59.888000
4,57e63954-a7ca-4af1-9ae4-a4aed0f89334,2020-01-01 01:49:15.450000,1,US,Android,False,battle,Super Overdrive,2019-12-30 04:45:54.467000,0.0,0,False,2-Star Win,campaign,215,16,206,4,2020-01-01,01:49:15.450000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3231353,84bb7e2c-3656-473d-addc-78a53e9a0411,2020-01-31 23:35:41.527000,1042,CA,iOS,False,battle,Super Overdrive,2017-03-25 17:27:18.042000,0.0,0,False,1-Star Win,campaign,83,67324,404,30,2020-01-31,23:35:41.527000
3231354,22aef3f0-4c8d-46d5-ba27-e432acfd730a,2020-01-31 23:36:02.916000,11,US,Android,True,battle,Super Overdrive,2020-01-20 01:03:35.359000,0.0,0,False,3-Star Win,campaign,218,310,601,19,2020-01-31,23:36:02.916000
3231355,d1316cfd-c37d-4980-aff7-fe1c5492db7a,2020-01-31 23:36:07.048000,0,GR,Android,False,battle,Super Overdrive,2020-01-31 22:39:05.389000,0.0,0,False,Loss,campaign,184,11,301,2,2020-01-31,23:36:07.048000
3231356,a5dd871a-bc54-4371-a1fb-226612035639,2020-01-31 23:37:11.606000,2,MX,Android,True,battle,Super Overdrive,2020-01-29 20:03:25.577000,0.0,0,False,1-Star Win,campaign,115,84,204,10,2020-01-31,23:37:11.606000
3231357,0ba8e642-e851-4b0f-a7ab-4befe98878f9,2020-01-31 23:37:12.854000,35,EC,Android,False,battle,Super Overdrive,2019-12-27 19:11:30.088000,0.0,0,False,1-Star Win,campaign,98,278,701,18,2020-01-31,23:37:12.854000

In [5]:
battle['seconds_since_midnight'] = (
    pd.to_timedelta(
        battle['event_timex'].astype(str)
    ).dt.total_seconds()
)

# Create 12 bins of 2 hours each
battle['time_span'] = (
    (battle['seconds_since_midnight'] // 7200).astype(int)
)

# Create readable labels
battle['time_span'] = battle['time_span'].apply(
    lambda x: f'{x*2:02d}:00–{(x+1)*2:02d}:00'
)

In [66]:
battle

,user_id,event_time,user_point_in_lifetime,user_country,user_device_platform,user_marketing_user,event_type,game_name,user_install_time,user_cumulative_iap_revenue,...,event_battle_result,custom_battle_type,event_battle_duration,user_cumulative_battles,custom_map_id,user_rank,event_date,event_timex,seconds_since_midnight,time_span
0,9b685c09-524a-43e2-a6f9-b970a438fd33,2020-01-01 01:47:39.837000,2,RU,Android,False,battle,Super Overdrive,2019-12-29 08:38:21.177000,0.0,...,2-Star Win,campaign,141,138,203,11,2020-01-01,01:47:39.837000,6459.837,00:00–02:00
1,2b31d675-2007-4689-9f0c-cd67bb3e04c3,2020-01-01 01:47:45.451000,0,VE,Android,False,battle,Super Overdrive,2019-12-31 20:00:28.676000,0.0,...,3-Star Win,campaign,177,10,205,3,2020-01-01,01:47:45.451000,6465.451,00:00–02:00
2,139b74ef-3178-42c1-a4b5-6f8e8b490af3,2020-01-01 01:48:52.189000,46,US,Android,False,battle,Super Overdrive,2019-11-15 15:56:15.092000,0.0,...,3-Star Win,campaign,200,1398,505,30,2020-01-01,01:48:52.189000,6532.189,00:00–02:00
3,044d0f29-97b7-4abe-874c-38161bc5cf29,2020-01-01 01:48:59.888000,0,MX,Android,False,battle,Super Overdrive,2020-01-01 00:58:12.397000,0.0,...,2-Star Win,campaign,173,12,204,2,2020-01-01,01:48:59.888000,6539.888,00:00–02:00
4,57e63954-a7ca-4af1-9ae4-a4aed0f89334,2020-01-01 01:49:15.450000,1,US,Android,False,battle,Super Overdrive,2019-12-30 04:45:54.467000,0.0,...,2-Star Win,campaign,215,16,206,4,2020-01-01,01:49:15.450000,6555.450,00:00–02:00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3231353,84bb7e2c-3656-473d-addc-78a53e9a0411,2020-01-31 23:35:41.527000,1042,CA,iOS,False,battle,Super Overdrive,2017-03-25 17:27:18.042000,0.0,...,1-Star Win,campaign,83,67324,404,30,2020-01-31,23:35:41.527000,84941.527,22:00–24:00
3231354,22aef3f0-4c8d-46d5-ba27-e432acfd730a,2020-01-31 23:36:02.916000,11,US,Android,True,battle,Super Overdrive,2020-01-20 01:03:35.359000,0.0,...,3-Star Win,campaign,218,310,601,19,2020-01-31,23:36:02.916000,84962.916,22:00–24:00
3231355,d1316cfd-c37d-4980-aff7-fe1c5492db7a,2020-01-31 23:36:07.048000,0,GR,Android,False,battle,Super Overdrive,2020-01-31 22:39:05.389000,0.0,...,Loss,campaign,184,11,301,2,2020-01-31,23:36:07.048000,84967.048,22:00–24:00
3231356,a5dd871a-bc54-4371-a1fb-226612035639,2020-01-31 23:37:11.606000,2,MX,Android,True,battle,Super Overdrive,2020-01-29 20:03:25.577000,0.0,...,1-Star Win,campaign,115,84,204,10,2020-01-31,23:37:11.606000,85031.606,22:00–24:00
3231357,0ba8e642-e851-4b0f-a7ab-4befe98878f9,2020-01-31 23:37:12.854000,35,EC,Android,False,battle,Super Overdrive,2019-12-27 19:11:30.088000,0.0,...,1-Star Win,campaign,98,278,701,18,2020-01-31,23:37:12.854000,85032.854,22:00–24:00

In [6]:
import numpy as np
battle['day_type'] = np.where(
    pd.to_datetime(battle['event_time']).dt.dayofweek >= 5,
    'Weekend',
    'Weekday'
)

In [24]:
battle.pivot_table(
    values='event_battle_duration',
    columns=['time_span','user_device_platform'],
    index='event_battle_result',
    aggfunc=['median']
)

                          median                                               \
time_span            00:00–02:00        02:00–04:00        04:00–06:00
user_device_platform     Android    iOS     Android    iOS     Android    iOS
event_battle_result
1-Star Win                  91.0   89.0        91.0   89.0        91.0   89.0
2-Star Win                 168.0  166.0       168.0  167.0       168.0  167.0
3-Star Win                 197.0  197.0       196.0  197.0       196.0  197.0
Loss                       116.0  116.0       116.0  115.0       116.0  113.0

                                                            ...              \
time_span            06:00–08:00        08:00–10:00         ... 14:00–16:00
user_device_platform     Android    iOS     Android    iOS  ...     Android
event_battle_result                                         ...
1-Star Win                  91.0   89.0        91.0   90.0  ...        91.0
2-Star Win                 168.0  167.0       168.0  167.0  ...       169.0
3-Star Win                 197.0  197.0       197.0  197.0  ...       196.0
Loss                       117.0  113.0       117.0  114.0  ...       119.0

                                                                               \
time_span                   16:00–18:00        18:00–20:00        20:00–22:00
user_device_platform    iOS     Android    iOS     Android    iOS     Android
event_battle_result
1-Star Win             90.0        92.0   90.0        92.0   91.0        92.0
2-Star Win            168.0       169.0  168.0       170.0  169.0       170.0
3-Star Win            197.0       196.0  197.0       196.0  197.0       197.0
Loss                  119.0       118.0  119.0       118.0  118.0       119.0


time_span                   22:00–24:00
user_device_platform    iOS     Android    iOS
event_battle_result
1-Star Win             91.0        92.0   91.0
2-Star Win            170.0       170.0  170.0
3-Star Win            197.0       196.0  197.0
Loss                  120.0       118.0  115.0

[4 rows x 24 columns]